server:
  port: 8080

spring:
  application:
    name: api-gateway
  codec:
    max-in-memory-size: 10MB
  cloud:
    compatibility-verifier:
      enabled: false
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - http://localhost:5173
              - http://127.0.0.1:5173
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
      routes:
        - id: salud-bff
          uri: http://localhost:8097
          predicates:
            - Path=/api/portal/**
          filters:
            - StripPrefix=0

        - id: ms-listas-espera
          uri: http://localhost:8083
          predicates:
            - Path=/api/listas-espera/**,/lista-espera/**,/pacientes/**
          filters:
            - StripPrefix=0

        - id: ms-notificaciones
          uri: http://localhost:8085
          predicates:
            - Path=/api/notificaciones/**
          filters:
            - StripPrefix=0

        - id: ms-optimizacion
          uri: http://localhost:8084
          predicates:
            - Path=/optimizacion/**,/citas/**,/medicos/**,/horarios/**
          filters:
            - StripPrefix=0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: false
