-- InsForge initial schema for the current Spring Boot microservices
-- Tables based on JPA entities in:
-- - ms-gestionpacientes
-- - ms-optimizacion
-- - ms-notificaciones

CREATE TABLE IF NOT EXISTS paciente (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(255),
    apellido VARCHAR(255),
    dni VARCHAR(50),
    telefono VARCHAR(50),
    email VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS medico (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(255),
    especialidad VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS lista_espera (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    paciente_id BIGINT NOT NULL,
    interconsulta VARCHAR(255),
    gravedad VARCHAR(10) NOT NULL,
    estado VARCHAR(20) NOT NULL,
    CONSTRAINT fk_lista_espera_paciente
        FOREIGN KEY (paciente_id) REFERENCES paciente (id)
        ON DELETE CASCADE,
    CONSTRAINT chk_lista_espera_gravedad
        CHECK (gravedad IN ('BAJA', 'MEDIA', 'ALTA')),
    CONSTRAINT chk_lista_espera_estado
        CHECK (estado IN ('PENDIENTE', 'ASIGNADA', 'FINALIZADA'))
);

CREATE INDEX IF NOT EXISTS idx_lista_espera_paciente_id ON lista_espera (paciente_id);

CREATE TABLE IF NOT EXISTS horario (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    medico_id BIGINT NOT NULL,
    fecha DATE,
    hora_inicio TIME,
    hora_fin TIME,
    disponible BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT fk_horario_medico
        FOREIGN KEY (medico_id) REFERENCES medico (id)
        ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_horario_medico_id ON horario (medico_id);
CREATE INDEX IF NOT EXISTS idx_horario_fecha ON horario (fecha);

CREATE TABLE IF NOT EXISTS cita (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    paciente_id BIGINT,
    medico_id BIGINT,
    fecha_hora TIMESTAMP,
    estado VARCHAR(20) NOT NULL,
    CONSTRAINT fk_cita_medico
        FOREIGN KEY (medico_id) REFERENCES medico (id)
        ON DELETE SET NULL,
    CONSTRAINT chk_cita_estado
        CHECK (estado IN ('CONFIRMADA', 'CANCELADA', 'REASIGNADA'))
);

CREATE INDEX IF NOT EXISTS idx_cita_paciente_id ON cita (paciente_id);
CREATE INDEX IF NOT EXISTS idx_cita_medico_id ON cita (medico_id);
CREATE INDEX IF NOT EXISTS idx_cita_fecha_hora ON cita (fecha_hora);

CREATE TABLE IF NOT EXISTS notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    paciente_id BIGINT,
    tipo VARCHAR(50) NOT NULL,
    mensaje VARCHAR(2000) NOT NULL,
    estado VARCHAR(20) NOT NULL,
    creado_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    enviado_at TIMESTAMP,
    intentos_envio INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT chk_notifications_tipo
        CHECK (tipo IN (
            'CITA_CONFIRMADA',
            'CITA_CANCELADA',
            'RECORDATORIO_CITA',
            'CAMBIO_HORARIO',
            'PACIENTE_ASIGNADO',
            'CAMBIO_PRIORIDAD',
            'POSICION_ACTUALIZADA',
            'ACTUALIZACION_ESTADO',
            'ELIMINACION_LISTA_ESPERA'
        )),
    CONSTRAINT chk_notifications_estado
        CHECK (estado IN ('PENDIENTE', 'ENVIADA', 'FALLIDA', 'REINTENTANDO'))
);

CREATE INDEX IF NOT EXISTS idx_notifications_paciente_id ON notifications (paciente_id);
CREATE INDEX IF NOT EXISTS idx_notifications_estado ON notifications (estado);
CREATE INDEX IF NOT EXISTS idx_notifications_tipo ON notifications (tipo);


