apiVersion: v1
kind: Secret
metadata:
  name: insforge-secrets
  namespace: insforge
type: Opaque
stringData:
  DB_URL: "jdbc:postgresql://ep-shy-hall-ai8fgqi2-pooler.c-4.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require"
  DB_USERNAME: "neondb_owner"
  DB_PASSWORD: "npg_Viz5aYF6NSuO"
  JWT_SECRET: "miClaveSecretaSuperSeguraParaJWT2024SaludRedNorte"
