server:
  port: 8083

spring:
  application:
    name: ms-listas-espera
  datasource:
    url: ${DB_URL:jdbc:postgresql://ep-shy-hall-ai8fgqi2-pooler.c-4.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require}
    driverClassName: ${DB_DRIVER:org.postgresql.Driver}
    username: ${DB_USERNAME:neondb_owner}
    password: ${DB_PASSWORD:npg_Viz5aYF6NSuO}
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2
      connection-timeout: 30000
      idle-timeout: 600000
  jpa:
    database-platform: ${DB_DIALECT:org.hibernate.dialect.PostgreSQLDialect}
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:update}
    show-sql: ${JPA_SHOW_SQL:true}
  flyway:
    enabled: true
    table: flyway_ms_listas_espera
    baseline-on-migrate: true
  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: ${FEIGN_CONNECT_TIMEOUT:2000}
            readTimeout: ${FEIGN_READ_TIMEOUT:5000}

eureka:
  client:
    enabled: false


management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true

jwt:
  secret: miClaveSecretaSuperSeguraParaJWT2024SaludRedNorte
  expiration: 86400000
