server:
  port: 8083

spring:
  application:
    name: ms-listas-espera
  datasource:
    url: ${DB_URL:jdbc:h2:mem:testdb}
    driverClassName: ${DB_DRIVER:org.h2.Driver}
    username: ${DB_USERNAME:sa}
    password: ${DB_PASSWORD:password}
  h2:
    console:
      enabled: ${H2_CONSOLE_ENABLED:true}
  jpa:
    database-platform: ${DB_DIALECT:org.hibernate.dialect.H2Dialect}
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:update}
    show-sql: ${JPA_SHOW_SQL:true}
  flyway:
    enabled: false
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: ${FEIGN_CONNECT_TIMEOUT:2000}
            readTimeout: ${FEIGN_READ_TIMEOUT:5000}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true


management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true

